apiVersion: v1
kind: Service
metadata:
  name: calendar-app
  namespace: calendar
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: calendar-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
